import {
  pgTable,
  serial,
  text,
  varchar,
  integer,
  boolean,
  timestamp,
  date,
} from 'drizzle-orm/pg-core'

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  resetPasswordToken: varchar('reset_password_token', { length: 255 }),
  resetPasswordExpiration: timestamp('reset_password_expiration', {
    withTimezone: true,
    mode: 'date',
  }),
  salt: varchar('salt', { length: 255 }),
  hash: varchar('hash', { length: 2000 }),
  loginAttempts: integer('login_attempts').default(0),
  lockUntil: timestamp('lock_until', { withTimezone: true, mode: 'date' }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
})

export const packages = pgTable('packages', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  category: varchar('category', { length: 50 }).notNull(),
  tier: varchar('tier', { length: 50 }),
  shortLabel: varchar('short_label', { length: 100 }),
  departureDate: date('departure_date').notNull(),
  durationDays: integer('duration_days').notNull(),
  departureCity: varchar('departure_city', { length: 100 }).notNull(),
  airline: varchar('airline', { length: 100 }),
  makkahHotel: varchar('makkah_hotel', { length: 255 }),
  madinahHotel: varchar('madinah_hotel', { length: 255 }),
  priceMode: varchar('price_mode', { length: 50 }).notNull(),
  price: integer('price'),
  minimumDeposit: integer('minimum_deposit'),
  totalSeats: integer('total_seats'),
  remainingSeats: integer('remaining_seats'),
  packageStatus: varchar('package_status', { length: 50 }).notNull(),
  featuredOnHomepage: boolean('featured_on_homepage').default(false).notNull(),
  brochureFile: varchar('brochure_file', { length: 500 }),
  packageSummary: text('package_summary').notNull(),
  inclusions: text('inclusions').array(),
  exclusions: text('exclusions').array(),
  requirements: text('requirements').array(),
  itinerarySummary: text('itinerary_summary'),
  paymentNotes: text('payment_notes'),
  badgeText: varchar('badge_text', { length: 100 }),
  seoTitle: varchar('seo_title', { length: 255 }),
  seoDescription: text('seo_description'),
  ogImage: varchar('og_image', { length: 500 }),
  publishedAt: timestamp('published_at', { withTimezone: true, mode: 'date' }),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
})

export const leads = pgTable('leads', {
  id: serial('id').primaryKey(),
  leadType: varchar('lead_type', { length: 50 }).notNull(),
  packageId: integer('package_id').references(() => packages.id),
  fullName: varchar('full_name', { length: 255 }).notNull(),
  phone: varchar('phone', { length: 50 }).notNull(),
  nik: varchar('nik', { length: 50 }),
  fatherName: varchar('father_name', { length: 255 }),
  gender: varchar('gender', { length: 20 }),
  birthDate: date('birth_date'),
  city: varchar('city', { length: 100 }),
  message: text('message'),
  ktpFile: varchar('ktp_file', { length: 500 }),
  sourcePage: varchar('source_page', { length: 255 }),
  sourceCampaign: varchar('source_campaign', { length: 255 }),
  status: varchar('status', { length: 50 }).default('baru').notNull(),
  internalNotes: text('internal_notes'),
  privacyConsentGiven: boolean('privacy_consent_given').default(false).notNull(),
  privacyConsentAt: timestamp('privacy_consent_at', { withTimezone: true, mode: 'date' }),
  submittedAt: timestamp('submitted_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
})
